from typing import Protocol
from uuid import UUID

from app.domain.entities import ConversationEntity, MessageEntity


class ConversationRepository(Protocol):
    async def get_by_id(self, conversation_id: UUID) -> ConversationEntity | None: ...
    async def list_by_user(self, user_id: UUID, limit: int = 50,
                           offset: int = 0) -> list[ConversationEntity]: ...
    async def create(self, conversation: ConversationEntity) -> ConversationEntity: ...
    async def update(self, conversation: ConversationEntity) -> ConversationEntity: ...
    async def delete(self, conversation_id: UUID) -> None: ...
    async def add_message(self, message: MessageEntity) -> MessageEntity: ...
    async def get_messages(self, conversation_id: UUID,
                           limit: int = 100) -> list[MessageEntity]: ...
