from typing import Protocol
from uuid import UUID

from app.domain.entities import DoctorRoleEntity
from app.infrastructure.persistence.models.doctor import Favorite


class DoctorRepository(Protocol):
    async def get_by_id(self, doctor_id: UUID) -> DoctorRoleEntity | None: ...
    async def list_active(self, specialty: str | None = None, title: str | None = None,
                          order_by_rating: bool = False) -> list[DoctorRoleEntity]: ...
    async def list_all(self, lifecycle_state: str | None = None) -> list[DoctorRoleEntity]: ...
    async def save(self, doctor: DoctorRoleEntity) -> DoctorRoleEntity: ...
    async def delete(self, doctor_id: UUID) -> None: ...
    async def activate(self, doctor_id: UUID) -> DoctorRoleEntity: ...
    async def deactivate(self, doctor_id: UUID) -> None: ...
    async def toggle_favorite(self, user_id: UUID, doctor_id: UUID) -> str: ...
    async def get_favorites(self, user_id: UUID) -> list[Favorite]: ...
