from typing import Protocol
from uuid import UUID

from app.domain.entities import KnowledgeDocEntity


class KnowledgeRepository(Protocol):
    async def get_by_id(self, doc_id: UUID) -> KnowledgeDocEntity | None: ...
    async def list_all(self) -> list[KnowledgeDocEntity]: ...
    async def save(self, doc: KnowledgeDocEntity) -> KnowledgeDocEntity: ...
    async def delete(self, doc_id: UUID) -> None: ...
    async def get_latest_version(self, filename: str) -> KnowledgeDocEntity | None: ...
    async def update_status(self, doc_id: UUID, status: str) -> None: ...
    async def flush(self) -> None: ...
